language: node_js

git:
  depth: 1 # No need for commits history

branches:
  only: master # Do not build PR branches

stages:
  - name: Test

jobs:
  include:
    # To speed up Travis build, use one job per Platform + Node.js version combination
    - name: 'Prettier check updated, Lint updated, Commitlint - Node.js v12'
      if: type = pull_request
      node_js: 12
      script: npm run prettier-check-updated && npm run lint-updated && npm run commitlint-ci-pull-request
    - name: 'Lint - Node.js v12'
      if: type = push
      node_js: 12
      script: npm run lint
